[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/boutique"
  to = "/boutique.html"
  status = 200

[[redirects]]
  from = "/entretien"
  to = "/entretien.html"
  status = 200

[[redirects]]
  from = "/profil"
  to = "/profil.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[build.environment]
  NODE_VERSION = "18" 